### ISSUE TITLE
Define user meta storage structure

### ISSUE THREAD

**Issue by troehrkasse** [Flinlock/appointments-plus#3]
- [x] Design a structure for storing package information via user meta.

The structure is  like so: ['appointment_packages'][] where

$packages is an array of package objects that contain these values:

- 'package_id' => Package ID number. This is the same as the ID number of the Woocommerce product.
- 'appointment_id' => Product ID number of the individual appointment Woocommerce product.
- 'quantity_remaining' => How many appointments are remaining in the package.
- 'purchase_type' => How the package was purchased (paid for normally, manually entered, etc)
- 'order_id' => the associated Woocommerce order ID, if applicable. Can be NULL if no order.

 
- [x] Determine and record the appropriate Wordpress functions for create/update/delete of this information
- [x] Determine the most appropriate points at which to execute create/update/delete, as needed.
